name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Utilisez "main" si votre branche principale est main
  pull_request:
    branches:
      - master  # Utilisez "main" si votre branche principale est main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -t mon-projet .

      - name: Push Docker image to Docker Hub
        run: |
          docker tag mon-projet ${{ secrets.DOCKERHUB_USERNAME }}/mon-projet:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mon-projet:latest
