name: Player information Workflow

on:
    workflow_dispatch:
      inputs:
        usernames:
          description: 'username of the player'
          required: true
          type: string
        level:
          discription: 'level of the player'
          required: true
          type: string
        class:
          discription: 'the class of the player'
          required: true
          type: string
          options:
            -jedi
            -sith
            -rebel

  jobs:
    player_info:
      runs-on: ubuntu-latest

    steps:
      -name: display player information
       run:
          echo "Le joueur <username> est de niveau <level> et joue un <class>."

        